BaseUrl= "https://cc8848.github.io/"
LanguageCode= "en-US"
Title= "37º空间-个人博客"
paginate = 5
DisqusShortname = "37º空间-个人博客"
Copyright = "All rights reserved - 2019"
canonifyurls = true

[author]
  name = "zj"

[params]
  description = "this is my description"
  cover = "images/user.jpg"
  author = "zj"
  authorlocation = ""
  authorwebsite = ""
  bio= "my bio"
  logo = "images/user.png"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = "zj"
  twitterName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  email                    = "cc8848@163.com"
  github                   = "//github.com/cc8848"
  linkedin                 = "//linkedin.com/in/you"
  facebook                 = "//facebook.com/you"
  googleplus               = "//google.com/you"
  twitter                  = "//twitter.com/you" 
  px500                    = "//px500"
  instagram                = "//instagram.com/you"
  include_rss              = true                          # include RSS <link> tag in <head> and show RSS icon
  